version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    restart: always
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      # - '9093:9093'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_DELETE_TOPIC_ENABLE=true
      # - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      # - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      # - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      # - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    restart: always
    depends_on:
      - 'zookeeper'
  initializer:
    image: 'bitnami/kafka:latest'
    depends_on:
      - 'kafka'
    entrypoint: '/bin/bash'
    command: >
      -c "sleep 15 ;
      kafka-topics.sh --create --zookeeper zookeeper:2181 --replication-factor 1 --partitions 20 --topic flows ;"
  grafana:
    build: ../grafana
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./grafana/datasources-ch.yml:/etc/grafana/provisioning/datasources/datasources-ch.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  prometheus:
    image: 'prom/prometheus'
    ports:
      - '9090:9090'
    restart: always
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  goflow:
    image: 'cloudflare/goflow:latest'
    depends_on:
      - 'initializer'
    ports:
      - '8080:8080'
      - '6343:6343/udp'
      - '2055:2055/udp'
      - '2056:2056/udp'
    restart: always
    entrypoint: '/bin/sh'
    command: >
      -c "sleep 15 ;
      /goflow -kafka.brokers kafka:9092
      -kafka.topic flows
      -proto.fixedlen=true
      -loglevel=debug
      "
  db:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123
    volumes:
      - ./clickhouse:/docker-entrypoint-initdb.d/
      - ../pb-ext/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto
    depends_on:
      - 'kafka'
  # inserter:
  #   build: ../inserter
  #   ports:
  #     - 2103:2103
  #   depends_on:
  #     - 'kafka'
